<html>
	<!-- Before you insult our website coding skills, please note that it is autogenerated with PHP, so the HTML is ugly. -->
	<?php include_once("header.php"); ?>
	<body>
		<?php include_once("nav.php"); ?>
		<div class="container">
			<div class="well">
				<div align="center">
					<h2>Welcome to <?php echo $sitename; ?>!</h2>
				</div>
				<hr>
				<h3>General FAQ/Site Info</h3>
				<div class="list-group">
					<?php
						echo qali("What is this website?", "A website that has Java/Minecraft coding related tutorials and references.");
						echo qali("What sort of stuff is on this website?", "General references for Java, Minecraft, and Bukkit API programming, along with tutorials on all 3 of those subjects.");
						echo qali("Who created this website?", "Herpingdo, with some assistance from jordinjm");
						echo qali("How do I get to the content?", "Click one of the subjects on the top navbar, and select what you would like from the menu that pops up.");
						echo qali("Why this website?", "Because you're already on it, plus it is written by experienced coders.");
						echo qali("How can I help improve x?", "Submit a pull request on our GitHub, which you can find at https://github.com/herpingdo/bukkithelp/");
						echo qali("I have an idea for the site, but I don't wish to code it myself. Where can I suggest it?", "Suggest it here: http://site/suggest.php");
					?>
				</div>

			</div>
		</div>
	</body>
</html>