<html>
	<!-- Before you insult our website coding skills, please note that it is autogenerated with PHP, so the HTML is ugly. -->
	<?php include_once("header.php"); ?>
	<body>
		<?php include_once("nav.php"); include_once("vars.php"); ?>

		<div class="container">
			<div class="well">
				<div align="center">
					<h2>Java Tutorials</h2>
				</div>
				<hr>
				<table class="table table-striped table-bordered table-condensed table-hover">
					<tr>
						<td>ID</td>
						<td>Name</td>
						<td>Description</td>
					</tr>
				<?php
					//echo var_dump(readall("tutorials/java/1.txt"));
				//echo "PENIS 2" . $f;
					//echo var_dump(tutorial("1"));
					foreach (scandir("tutorials/java") as $fi) {
						if ($fi == "." || $fi == "..") continue;
						$read = readall("tutorials/java/" . $fi);
						$id = str_replace(".txt", "", $fi);
						$name = $read[0];
						$desc = $read[1];

						//var_dump($line);
						//$line = $line[0];
						echo <<<"EOF"
							<tr>
								<td><a href="tview.php?cat={$f}&id={$id}">{$id}</a></td>
								<td><a href="tview.php?cat={$f}&id={$id}">{$name}</a></td>
								<td>{$desc}</td>
							</tr>

							
EOF;
						echo $line;
						//echo 
					}
				?>
				</table>

			</div>
		</div>
	</body>
</html>