<html>
	<!-- Before you insult our website coding skills, please note that it is autogenerated with PHP, so the HTML is ugly. -->
	<?php include_once("header.php"); ?>
	<body>
		<?php include_once("nav.php"); include_once("vars.php"); ?>

		<div class="container">
			<div class="well">
				<?php
					$category = $_GET["cat"];
					$id = $_GET["id"];
					if (!isset($category) || !isset($id)) {
						echo "<h1>Invalid ID/Category specified.</h1>";
					} else {
						echo tutorial2($id, $category);
					}
				?>
			</div>
		</div>
	</body>
</html>